name: Core
on: push
defaults:
  run:
    working-directory: core
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
