name: icons-release
on: workflow_dispatch
defaults:
  run:
    working-directory: icons
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: icons/package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Create Release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm run release:patch
      - name: Commit files
        uses: actions/checkout@v2
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push --follow-tags
