name: icons-publish
on:
  create:
    tags:
      - '@haiilo/catalyst-icons/v*'
defaults:
  run:
    working-directory: icons
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: icons/package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: icons/package.json
