name: 'Initialize'

on:
  workflow_call:
    inputs:
      package-lock:
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ${{inputs.package-lock}}
      - name: Install
        run: npm ci
