name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd ./core 
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
