name: 'Tokens'

on:
  push:
    branches:
      - '*'
    # paths:
    #   - 'tokens/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./install.yml
      - name: Build
        run: pnpm run build:tokens
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: update tokens'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
