name: 'Tokens'

on:
  push:
    branches:
      - '*'
    # paths:
    #   - 'tokens/**'

jobs:
  install:
    uses: ./.github/workflows/install.yml
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build
        run: pnpm run build:tokens
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: update tokens'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
